### ISSUE TITLE
incomplete crud

### ISSUE THREAD

**Issue by hema1007** [skunal2222/git_new#7]
out od date
![44129379_1064241710406074_1822039420337913856_n](https://user-images.githubusercontent.com/38518860/52407741-163e9680-2af7-11e9-9116-69e6b04f7da1.jpg)

**Comment by hema1007** [comment]
aaaaa

**Comment by skunal2222** [comment]
thanks for motivate

**Comment by hema1007** [comment]
shant

**Comment by hema1007** [comment]
shant
